spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@devedu.hanboard.com.cn:11521:devbase
    username: eduresource
    password: eduresource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: oracle